version: "3"
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yogeshs
      - MONGO_INITDB_ROOT_PASSWORD=yogeshs
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=yogeshs
      - ME_CONFIG_MONGODB_ADMINPASSWORD=yogeshs
      - ME_CONFIG_MONGODB_URL=mongodb://yogeshs:yogeshs@mongodb:27017/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    x-develop: 
      watch:
        - path: ./src
          target: /home/app/node-docker/src
          action: sync
          ignore:
            - node_modules/
        - path: ./package.json    
          action: rebuild
    ports:
      - 3000:3000
      - 9222:9229
    # command: ["node", "--inspect=0.0.0.0:9229", "dist/server-app.js"]